version: '3'

services:
  build-mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=project2"

  docker-build:
    build: .
    depends_on:
      - build-mysql
    network_mode: host
    restart: always